--materia dado
DECLARE @NUMERO_ANTERIOR2 INT; -- seta o primeiro valor
DECLARE @NUMERO_ANTERIOR1 INT; -- seta o segundo valor a sequência
DECLARE @NUMERO_ATUAL INT; -- somatória dos dois valores anteriores
DECLARE @SEQUENCIA INT; -- len() da sequência em lista
-- DECLARE @LIMITE_MAXIMO INT; -- valor máximo para a sequência
DECLARE @CONTADOR_SEQUENCIA INT; --

-- SET @LIMITE_MAXIMO = 100;
SET @SEQUENCIA = 44; -- limita a posição para qualquer valor escolhido
SET @CONTADOR_SEQUENCIA = 3;

SET @NUMERO_ANTERIOR2 = 0;
SET @NUMERO_ANTERIOR1 = 1;
PRINT 'POSIÇÃO 1 --> 0';
PRINT 'POSIÇÃO 2 --> 1';
WHILE @CONTADOR_SEQUENCIA <= @SEQUENCIA
BEGIN
   SET @NUMERO_ATUAL = @NUMERO_ANTERIOR2 + @NUMERO_ANTERIOR1;
   PRINT 'POSIÇÃO ' + TRIM(STR(@CONTADOR_SEQUENCIA,10,0)) + ' --> ' + TRIM(STR(@NUMERO_ATUAL, 10,0));
   -- IF @NUMERO_ATUAL > @LIMITE_MAXIMO BREAK; 
   SET  @NUMERO_ANTERIOR2 = @NUMERO_ANTERIOR1;
   SET @NUMERO_ANTERIOR1 = @NUMERO_ATUAL;
   SET @CONTADOR_SEQUENCIA = @CONTADOR_SEQUENCIA + 1;
END;
